blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'  ## 이 부분 누락되지 않도록 주의!!!

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
]

shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('excel/', views.response_excel),
    path('image/', views.response_image),
    path('mysum/<int:x>/<int:y>/', views.my_sum),
    path('archives/<yyyy:year>/', views.year_archive),
    path('', views.item_list, name='item_list'),
    path('test_templates/', views.test_templates),  # 추가
    path('<int:pk>/', views.item_detail, name='item_detail'),
]

work19/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('pizzas/', include('pizzas.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:                                       # 추가 2
    import debug_toolbar                                 # 추가 2
    urlpatterns += [                                     # 추가 2
        path('__debug__/', include(debug_toolbar.urls)), # 추가 2
    ]

shop/models.py
from django.db import models
from pytz import timezone
from django.conf import settings
from django.urls import reverse

def local_time(input_time):
    fmt = '%Y-%m-%d %H:%M'
    my_zone = timezone(settings.TIME_ZONE)
    my_local_time = input_time.astimezone(my_zone)
    return my_local_time.strftime(fmt)

class Item(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    photo = models.ImageField()
    tags = models.ManyToManyField('Tag', blank=True, related_name='tags')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.name

    def tagged(self):
        ts = self.tags.all()
        return  '{' + ', '.join(map(str, ts)) + '}'

        return tag_string
    tagged.short_description = '태그 집합'

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})


class Review(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE,
                             related_name='reviews', verbose_name='아이템')
    message = models.TextField('상품후기')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-item__id', '-id']
    def updated(self):
        return local_time(self.updated_at)

    updated.short_description = '수정 일시'

    def __str__(self):
        return self.message



class Tag(models.Model):
    name = models.CharField('태그', max_length=100, unique=True)

    class Meta:
        ordering = ['-id']  # Tag 객체의 기본 정렬 순서 지정

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Item, Tag
from django.http import HttpResponse
import requests
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont
import pandas as pd                           # 엑셀 요청 처리
from io import BytesIO
from urllib.parse import quote


def response_excel(request):
	df = pd.DataFrame([
		[100, 110, 120],
		[200, 210, 220],
	])

	io = BytesIO()
	df.to_excel(io)
	io.seek(0)

	encoded_filename = quote('pandas.xlsx')  # '.xls'가 아니라 '.xlsx'
	response = HttpResponse(io, content_type='application/vnd.ms-excel')
	response['Content-Disposition'] = \
		"attachment; filename*=utf-8''{}".format(encoded_filename)
	return response


def response_image(request):
	ttf_path = 'C:/Windows/Fonts/malgun.ttf' # 윈도우, 맥: '/Library/Fonts/AppleGothic.ttf'

	# 이미지 파일 다운로드 혹은 로컬 디스크 상의 이미지 직접 열기
	image_url = 'http://www.flowermeaning.com/flower-pics/Calla-Lily-Meaning.jpg'
	res = requests.get(image_url) # 서버로 HTTP GET 요청하여, 응답 획득
	io = BytesIO(res.content) # 응답의 Raw Body 메모리 파일 객체 BytesIO 인스턴스 생성
	io.seek(0) # 파일의 처음으로 커서를 이동

	canvas = Image.open(io).convert('RGBA') # 이미지 파일을 열고, RGBA 모드로 변환
	font = ImageFont.truetype(ttf_path, 40) # 지정 경로의 TrueType 폰트, 폰트 크기40
	draw = ImageDraw.Draw(canvas) # canvas에 대한 ImageDraw 객체 획득

	text = 'Smart IT, by logistex'
	left, top = 400, 400
	margin = 10
	width, height = font.getsize(text)
	right = left + width + margin
	bottom = top + height + margin
	draw.rectangle((left, top, right, bottom), (255, 255, 224))
	draw.text((left+15,top+15), text, font=font, fill=(20, 20, 20))

	response = HttpResponse(content_type='image/png')
	canvas.save(response, format='PNG') # HttpResponse의 유사 파일 객체 특성 활용
	return response


def year_archive(request, year):
    if year is not None:
        return HttpResponse('{}년도 자료 입니다.'.format(year))
    else:
        return HttpResponse('해당년도 자료는 없습니다.'.format(year))

def my_sum(request, x, y):
    result = x + y
    output = '{} = {} + {}'.format(result, x, y)
    return HttpResponse(output)

def item_list(request):
    items = Item.objects.all()
    q = request.GET.get('q', '')  # 키값이 'q'로 지정된 값이 없으면 None이 반환됨
    if q:  # q가 널 아니면 qs에 filter 조건 추가
        items = items.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list': items,
        'q': q,
    })


class MyClass:
    x = 10
    y = 20

def test_templates(requset):
    from django.template import Context, Template
    import datetime       # USE_TZ = True
    from django.utils import timezone   # TIME_ZONE = 'Asia/Seoul'
    from dateutil.parser import parse

    # 맥락 변수 사전
    my_dict = {'first_name': 'haewoong', 'last_name': 'Shin'}
    my_obj = MyClass()
    my_list = [1, 2, 3, 4]
    my_date = datetime.datetime.now()
    local_time = timezone.localtime()
    my_b_date1 = datetime.date(2019, 12, 29)
    my_b_date2 = parse('2010-12-29')
    my_b_datetime = datetime.datetime(2010, 12, 29, 17, 34, 56)
    my_string = '사랑하지 않으려면 떠나라. Love it or leave it.'

    context = Context({'my_dict': my_dict, 'my_obj': my_obj, 'my_list': my_list,
                       'my_date': my_date, 'local_time': local_time,
                       'my_b_date1': my_b_date1, 'my_b_date2': my_b_date2,
                       'my_b_datetime': my_b_datetime, 'my_string': my_string,
                       })
    template = Template(
        "사전 < my_dict.last_name >: {{ my_dict.last_name }} <br/>"
        + "객체 < my_obj.x >: {{ my_obj.x }} {{ my_obj.y }} <br/>"
        + "리스트 < my_list.0 >: {{ my_list.0 }} {{ my_list.2 }}: {{ my_list.2 }} <br/>"
        + "< my_dict.first_name|title >: {{ my_dict.first_name|title }} <br/>"
        + "{% verbatim myblock %}{% now 'Y-m-d H:i:s' %}"
        + "{% endverbatim myblock %} : {% now 'Y-m-d H:i:s' %} <br/>"
        + "< my_date > : {{ my_date }} <br/>"
        + "< local_time >: {{ local_time }} <br/>"
        + "< my_b_date1 >: {{ my_b_date1 }} <br/>"
        + "< my_b_date2 >: {{ my_b_date2 }} <br/>"
        + "< my_b_date1|date:'SHORT_DATE_FORMAT' >: {{ my_b_date1|date:'SHORT_DATE_FORMAT' }} <br/>"
        + "(마지막에 점이 찍힘!! 필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_b_date1|date:'Y년 m월 d일' >: {{ my_b_date1|date:'Y년 m월 d일' }} <br/>"
        # + "< my_b_date|date:'LONG_DATE_FORMAT' >(???)': {{ my_b_date|date:'LONG_DATE_FORMAT' }} <br/>"
        # + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>" # 오류!!
        + "< my_b_datetime >: {{ my_b_datetime }} <br/>"
        + "< my_b_datetime|date:'Y년 m월 d일' > < my_b_datetime|time:'H시 i분 s초' >: "
            + "{{ my_b_datetime|date:'Y년 m월 d일' }}  {{ my_b_datetime|time:'H시 i분 s초' }} <br/>"
            + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatewords:'4' >: {{ my_string|lower|truncatewords:'4' }} <br/>"
            + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatechars:'12' >: {{ my_string|lower|truncatechars:'12' }} <br/>"
            +"(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
    )
    content = template.render(context)

    return HttpResponse(content)

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    all_tag = Tag.objects.all()
    mystr = item.tagged()
    my_tag = {}
    for t in all_tag:
        my_tag[t.name] = str(mystr).find(t.name)
    return render(request, 'shop/item_detail.html',
                  {'item': item, 'my_tag': my_tag})

shop/templates/shop/item_detail.html
{% extends './layout.html' %}
{% block content %}
{#    <a href="/blog/">게시판 목록으로 돌아가기</a><br/><br/>#}
    <a href="{% url 'shop:item_list' %}">게시판 목록으로 돌아가기</a><br/><br/>

    <table>
        <thead>
            <th>필드</th><th>내용</th>
        </thead>
        <tbody>
        <tr>
            <td width="10%">id:</td><td><input type="text" value={{ item.id }}></td>
        </tr>
        <tr>
            <td>아이템:</td><td><input type="text" value="{{ item.name }}" style="width:500px;"></td>
        </tr>
        <tr>
            <td>설명:</td><td><input type="text" value="{{ item.desc }}"  style="width:500px;"></td>
        </tr>
        <tr>
            <td>사진:</td><td>        {% if item.photo %}
            <img src="{{ item.photo.url }}" />
        {% endif %}</td>
        </tr>
        <tr>
            <td>게시 일시:</td><td><input type="text" value="{{ item.created_at }}" style="width:500px;"></td>
        </tr>
        <tr>
            <td>수정 일시:</td><td><input type="text" value="{{ item.updated_at }}" style="width:500px;"></td>
        </tr>
        <tr>
            <td>태그 집합:</td><td><input type="text" value="{{ item.tagged }}"></td>
        </tr>
        </tbody>
    </table>

    <br/>
    <br/>

    <table>
        <thead>
            <th>id</th>
            <th>후기</th>
            <th>작성 일시</th>
            <th>수정 일시</th>

        </thead>
        <tbody>
        {% for c in item.reviews.all %}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ c.message }}</td>
                <td>{{ c.created_at }}</td>
                <td>{{ c.updated }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> <br/>



{% endblock %}

shop/templates/shop/item_list.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>
    <hr>
    <table>
        <thead>
            <th>번호</th>
            <th>이름</th>
            <th>설명</th>
            <th>사진</th>
            <th>등록 일시</th>
            <th>수정 일시</th>
        </thead>
        <tbody>
            {% for item in item_list %}
            <tr>
                <td> {{ item.id }} </td>
                <td> <a href="{{ item.get_absolute_url }}">{{ item.name }}</a> </td>
                <td> {{ item.desc }} </td>
                <td> {{ item.photo }} </td>
                <td> {{ item.created_at }} </td>
                <td> {{ item.updated_at }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> <br/><br/>

    {{ request }} <br/>
    request.method: {{ request.method }} <br/>
    request.GET: {{ request.GET }} <br/>
    request.META: {{ request.META }}
    <hr/>
    {{ item_list }}
    <hr>
    {% for item in item_list %}
        {{ item }} <br>
    {% endfor %}
    <hr>
    {% for item in item_list %}
        {{ item.name }} #
        {{ item.desc }} #
        {{ item.photo }} #
        {{ item.created_at }} #
        {{ item.updated_at }} <br/>
        {% if item.photo %}
            <img src="{{ item.photo.url }}" />
        {% endif %} <br/>
    {% endfor %}
{% endblock %}

shop/templates/shop/layout.html
{% extends '../layout.html' %}

{% load static %}

{% block title %}
    {{ block.super }} shop
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <img src="{% static 'logo.png' %}" alt="shop logo image">
    <h2>shop in 217230120 site </h2>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script src="{% static 'shop/shop.js' %}"></script>
{% endblock %}